const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { allQuery, getQuery, runQuery } = require('../config/database');
const { auth } = require('../middleware/auth');
const { PERFIS, inferirPerfil } = require('../constants/access');

const router = express.Router();
const TECHNICAL_FIELDS = {
  CONCRETO: ['fck_mpa','classe','volume_solicitado','volume_recebido','usina','slump_especificado','temperatura','aditivo','elemento_concretado','localizacao','quantidade_corpos_prova_prevista','atividade_eap_id','rdo_id'],
  ACO: ['classe_aco','bitola','peso','comprimento','corrida','fabricante','certificado','condicao_visual'],
  CABOS: ['tipo_cabo','material_condutor','secao_nominal','classe_tensao','comprimento','bobina','certificado'],
  ELETRICOS: ['fabricante','modelo','numero_serie','potencia','tensao','codigo_patrimonial','garantia'],
  EQUIPAMENTOS: ['fabricante','modelo','numero_serie','potencia','tensao','codigo_patrimonial','garantia'],
  FOTOVOLTAICOS: ['fabricante','modelo','potencia_wp','palete','lote','faixa_series','flash_report','embalagem','quantidade_avariada'],
  ESTRUTURAS: ['fabricante','tipo_peca','desenho','lote','tratamento','espessura_galvanizacao','certificado','condicao_visual'],
  AGREGADOS: ['tipo_agregado','origem','granulometria','umidade','laudo']
};
const QUALITY_PROFILES = new Set([PERFIS.ADM, PERFIS.GESTOR_GERAL, PERFIS.GESTOR_QUALIDADE]);
const WRITE_PROFILES = new Set([PERFIS.ADM, PERFIS.GESTOR_GERAL, PERFIS.GESTOR_QUALIDADE, PERFIS.ALMOXARIFE]);
const APPLY_PROFILES = new Set([PERFIS.ADM, PERFIS.GESTOR_GERAL, PERFIS.GESTOR_OBRA]);
const uploadsDir = path.join(__dirname, '..', 'uploads');
const storage = multer.diskStorage({ destination: (req, _file, cb) => { const dir = path.join(uploadsDir, `tenant_${Number(req.tenantId)}`); fs.mkdirSync(dir, { recursive: true }); cb(null, dir); }, filename: (_req, file, cb) => cb(null, `${Date.now()}-${String(file.originalname || 'arquivo').replace(/[^a-zA-Z0-9._-]/g, '-')}`) });
const upload = multer({ storage, limits: { fileSize: 25 * 1024 * 1024 }, fileFilter: (_req, file, cb) => /\.(jpe?g|png|webp|gif|pdf|docx?|xlsx?)$/i.test(file.originalname || '') ? cb(null, true) : cb(new Error('Tipo de arquivo não permitido.')) });

const perfil = (req) => inferirPerfil(req.usuario);
const can = (req, allowed) => allowed.has(perfil(req)) || Boolean(req.usuario?.is_gestor);
const err = (res, error) => res.status(error.status || 400).json({ erro: error.message || 'Operação não permitida.' });
const log = (id, userId, acao, antes = null, depois = null) => runQuery('INSERT INTO material_historico (recebimento_id, usuario_id, acao, antes, depois) VALUES (?, ?, ?, ?, ?)', [id, userId, acao, antes ? JSON.stringify(antes) : null, depois ? JSON.stringify(depois) : null]);
const assertProject = async (id, tenant) => { const project = await getQuery('SELECT id FROM projetos WHERE id=? AND tenant_id=?', [id, tenant]); if (!project) { const e = new Error('Projeto inválido para o tenant ativo.'); e.status = 404; throw e; } return project; };
const assertReceipt = async (id, tenant) => { const item = await getQuery('SELECT m.*, t.codigo AS tipo_codigo, t.nome AS tipo_nome FROM material_recebimentos m LEFT JOIN material_tipos t ON t.id=m.tipo_id WHERE m.id=? AND m.tenant_id=?', [id, tenant]); if (!item) { const e = new Error('Recebimento não encontrado.'); e.status = 404; throw e; } return item; };
const balance = async (receipt) => { const used = await getQuery("SELECT COALESCE(SUM(quantidade),0) AS total FROM material_aplicacoes WHERE recebimento_id=? AND tipo_movimento IN ('Aplicação','Saída','Devolução','Descarte')", [receipt.id]); return Math.max(0, Number(receipt.quantidade_aprovada || 0) - Number(used?.total || 0)); };
const validTechnical = (code, data) => {
  const input = data && typeof data === 'object' && !Array.isArray(data) ? data : {};
  const fields = TECHNICAL_FIELDS[code] || [];
  const normalized = Object.fromEntries(Object.entries(input).filter(([key]) => fields.includes(key)));

  if (code === 'CONCRETO') {
    if (!String(normalized.elemento_concretado || '').trim()) {
      throw new Error('Informe em que elemento o concreto será utilizado.');
    }
    const quantidadePrevista = normalized.quantidade_corpos_prova_prevista;
    if (quantidadePrevista !== undefined && quantidadePrevista !== null && String(quantidadePrevista).trim() !== '') {
      const quantidade = Number(quantidadePrevista);
      if (!Number.isInteger(quantidade) || quantidade <= 0) {
        throw new Error('A quantidade prevista de corpos de prova deve ser um número inteiro maior que zero.');
      }
      normalized.quantidade_corpos_prova_prevista = quantidade;
    } else {
      delete normalized.quantidade_corpos_prova_prevista;
    }
  }

  return normalized;
};
const isReceiptLocked = (receipt) => receipt.status === 'Encerrado' || ['Aprovado', 'Aprovado com ressalva', 'Bloqueado', 'Reprovado'].includes(receipt.status_inspecao);
const hydrate = async (receipt) => {
  const [inspecoes, aplicacoes, evidencias, rncs, caminhoes, corpos, historico] = await Promise.all([
    allQuery('SELECT i.*, u.nome AS inspetor_nome FROM material_inspecoes i LEFT JOIN usuarios u ON u.id=i.inspetor_id WHERE i.recebimento_id=? ORDER BY i.criado_em DESC', [receipt.id]),
    allQuery('SELECT a.*, e.codigo_eap, e.descricao AS atividade_descricao, u.nome AS registrado_por_nome FROM material_aplicacoes a LEFT JOIN atividades_eap e ON e.id=a.atividade_eap_id LEFT JOIN usuarios u ON u.id=a.criado_por WHERE a.recebimento_id=? ORDER BY a.aplicado_em DESC', [receipt.id]),
    allQuery('SELECT * FROM material_evidencias WHERE recebimento_id=? ORDER BY criado_em DESC', [receipt.id]),
    allQuery('SELECT r.*, mr.rnc_id FROM material_rncs mr JOIN rnc r ON r.id=mr.rnc_id WHERE mr.recebimento_id=?', [receipt.id]),
    allQuery('SELECT * FROM material_caminhoes_concreto WHERE recebimento_id=? ORDER BY id', [receipt.id]),
    allQuery('SELECT * FROM material_corpos_prova WHERE recebimento_id=? ORDER BY id', [receipt.id]),
    allQuery('SELECT h.*, u.nome AS usuario_nome FROM material_historico h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE h.recebimento_id=? ORDER BY h.criado_em DESC,id DESC', [receipt.id])
  ]);
  return { ...receipt, dados_tecnicos: JSON.parse(receipt.dados_tecnicos || '{}'), saldo_disponivel: await balance(receipt), inspecoes, aplicacoes, evidencias, rncs, caminhoes, corpos_prova: corpos, historico };
};

router.get('/configuracao', auth, async (req, res) => { try { res.json({ tipos: await allQuery('SELECT * FROM material_tipos WHERE ativo=1 AND (tenant_id IS NULL OR tenant_id=?) ORDER BY nome', [req.tenantId]), unidades: await allQuery('SELECT * FROM material_unidades WHERE ativo=1 AND (tenant_id IS NULL OR tenant_id=?) ORDER BY nome', [req.tenantId]), campos_tecnicos: TECHNICAL_FIELDS }); } catch (e) { err(res, e); } });
router.post('/configuracao/tipos', auth, async (req,res) => { try { if(perfil(req)!==PERFIS.ADM) return res.status(403).json({erro:'Somente ADM administra o catálogo.'}); const b=req.body||{}; if(!String(b.codigo||'').match(/^[A-Z0-9_]{2,40}$/)||!String(b.nome||'').trim()) throw new Error('Código e nome do tipo são obrigatórios.'); const result=await runQuery('INSERT INTO material_tipos (tenant_id,codigo,nome,schema_campos,ativo) VALUES (?,?,?,?,?)',[req.tenantId,b.codigo,String(b.nome).trim(),JSON.stringify(b.schema_campos||{}),b.ativo===false?0:1]); res.status(201).json({id:result.lastID}); }catch(e){err(res,e);} });
router.patch('/configuracao/tipos/:id', auth, async (req,res) => { try { if(perfil(req)!==PERFIS.ADM) return res.status(403).json({erro:'Somente ADM administra o catálogo.'}); const b=req.body||{}; await runQuery('UPDATE material_tipos SET nome=COALESCE(?,nome), schema_campos=COALESCE(?,schema_campos), ativo=COALESCE(?,ativo) WHERE id=? AND tenant_id=?',[b.nome?String(b.nome).trim():null,b.schema_campos?JSON.stringify(b.schema_campos):null,typeof b.ativo==='boolean'?(b.ativo?1:0):null,req.params.id,req.tenantId]); res.json({mensagem:'Tipo atualizado.'}); }catch(e){err(res,e);} });
router.post('/configuracao/unidades', auth, async (req,res) => { try { if(perfil(req)!==PERFIS.ADM) return res.status(403).json({erro:'Somente ADM administra o catálogo.'}); const b=req.body||{}; if(!String(b.codigo||'').trim()||!String(b.nome||'').trim()) throw new Error('Código e nome são obrigatórios.'); const result=await runQuery('INSERT INTO material_unidades (tenant_id,codigo,nome,ativo) VALUES (?,?,?,1)',[req.tenantId,String(b.codigo).toUpperCase(),String(b.nome).trim()]); res.status(201).json({id:result.lastID}); }catch(e){err(res,e);} });
router.get('/indicadores/:projetoId', auth, async (req, res) => { try { await assertProject(req.params.projetoId, req.tenantId); const rows = await allQuery(`SELECT status_inspecao, COUNT(*) total FROM material_recebimentos WHERE tenant_id=? AND projeto_id=? GROUP BY status_inspecao`, [req.tenantId, req.params.projetoId]); const total = rows.reduce((n,r) => n + Number(r.total), 0); const rnc = await getQuery(`SELECT COUNT(*) total FROM material_rncs mr JOIN material_recebimentos m ON m.id=mr.recebimento_id JOIN rnc r ON r.id=mr.rnc_id WHERE m.tenant_id=? AND m.projeto_id=? AND r.status <> 'Encerrada'`, [req.tenantId, req.params.projetoId]); res.json({ total, por_inspecao: rows, rncs_abertas: Number(rnc?.total || 0) }); } catch (e) { err(res,e); } });
router.get('/projeto/:projetoId', auth, async (req, res) => { try { await assertProject(req.params.projetoId, req.tenantId); const q = String(req.query.q || '').trim(); const where = ['m.tenant_id=?','m.projeto_id=?']; const args = [req.tenantId, req.params.projetoId]; if (q) { where.push('(m.codigo LIKE ? OR m.nome_material LIKE ? OR m.fornecedor_nome LIKE ? OR m.lote LIKE ? OR m.nota_fiscal LIKE ? OR m.numero_serie LIKE ?)'); args.push(...Array(6).fill(`%${q}%`)); } for (const key of ['status_inspecao','fornecedor_id','tipo_id']) if (req.query[key]) { where.push(`m.${key}=?`); args.push(req.query[key]); } if (req.query.liberados === '1') where.push("m.status_inspecao IN ('Aprovado','Aprovado com ressalva')"); const list = await allQuery(`SELECT m.*, mt.codigo AS tipo_codigo, mt.nome AS tipo_nome, COALESCE(f.nome_fantasia, f.razao_social, m.fornecedor_nome) AS fornecedor_exibicao, u.nome AS recebido_por_nome, MAX(0, COALESCE(m.quantidade_aprovada,0) - COALESCE((SELECT SUM(a.quantidade) FROM material_aplicacoes a WHERE a.recebimento_id=m.id AND a.tipo_movimento IN ('Aplicação','Saída','Devolução','Descarte')),0)) AS saldo_disponivel FROM material_recebimentos m LEFT JOIN material_tipos mt ON mt.id=m.tipo_id LEFT JOIN fornecedores f ON f.id=m.fornecedor_id LEFT JOIN usuarios u ON u.id=m.recebido_por WHERE ${where.join(' AND ')} ORDER BY m.recebido_em DESC,m.id DESC`, args); res.json(list); } catch(e) { err(res,e); } });
router.get('/:id', auth, async (req,res) => { try { res.json(await hydrate(await assertReceipt(req.params.id, req.tenantId))); } catch(e) { err(res,e); } });
router.post('/', auth, async (req,res) => { try { if (!can(req, WRITE_PROFILES)) return res.status(403).json({erro:'Sem permissão para registrar recebimento.'}); const b=req.body||{}; await assertProject(b.projeto_id, req.tenantId); if (!b.nome_material || !(Number(b.quantidade_recebida)>0) || !b.unidade) throw new Error('Nome, quantidade e unidade são obrigatórios.'); const type = await getQuery('SELECT * FROM material_tipos WHERE id=? AND ativo=1 AND (tenant_id IS NULL OR tenant_id=?)', [b.tipo_id, req.tenantId]); if (!type) throw new Error('Tipo de material inválido.'); if (type.codigo==='OUTROS' && !String(b.tipo_outro||'').trim()) throw new Error('Descreva o tipo “Outros”.'); if (type.codigo==='CONCRETO' && String(b.unidade).toUpperCase()!=='M3') throw new Error('O recebimento de concreto deve ser registrado em metros cúbicos (M3).'); const next=await getQuery('SELECT COUNT(*)+1 n FROM material_recebimentos WHERE tenant_id=?',[req.tenantId]); const code=`MAT-${String(req.tenantId).padStart(3,'0')}-${String(next.n).padStart(6,'0')}`; const result=await runQuery(`INSERT INTO material_recebimentos (tenant_id,codigo,projeto_id,tipo_id,tipo_outro,codigo_material,nome_material,descricao,quantidade_recebida,unidade,recebido_em,recebido_por,fornecedor_id,fornecedor_nome,fabricante,pedido_compra_id,nota_fiscal,lote,numero_serie,local_armazenamento,observacoes,dados_tecnicos,status,rdo_id,criado_por,atualizado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, [req.tenantId,code,b.projeto_id,type.id,b.tipo_outro||null,b.codigo_material||null,b.nome_material,b.descricao||null,Number(b.quantidade_recebida),b.unidade,b.recebido_em||new Date().toISOString(),can(req,QUALITY_PROFILES)&&b.recebido_por?b.recebido_por:req.usuario.id,b.fornecedor_id||null,String(b.fornecedor_nome||'').trim()||null,b.fabricante||null,b.pedido_compra_id||null,b.nota_fiscal||null,b.lote||null,b.numero_serie||null,b.local_armazenamento||null,b.observacoes||null,JSON.stringify(validTechnical(type.codigo,b.dados_tecnicos)),b.rascunho?'Rascunho':'Aberto',b.rdo_id||null,req.usuario.id,req.usuario.id]); await log(result.lastID,req.usuario.id,'RECEBIMENTO_REGISTRADO',null,b); res.status(201).json(await hydrate(await assertReceipt(result.lastID,req.tenantId))); } catch(e){err(res,e);} });
router.put('/:id', auth, async (req,res) => { try { const old=await assertReceipt(req.params.id,req.tenantId); if(!can(req,WRITE_PROFILES) || isReceiptLocked(old)) return res.status(403).json({erro:'O recebimento só pode ser alterado antes da aprovação ou decisão final da inspeção.'}); const b=req.body||{}; const unidade=b.unidade||old.unidade; if(old.tipo_codigo==='CONCRETO'&&String(unidade).toUpperCase()!=='M3') throw new Error('O recebimento de concreto deve ser registrado em metros cúbicos (M3).'); const dadosTecnicos=validTechnical(old.tipo_codigo,b.dados_tecnicos ?? JSON.parse(old.dados_tecnicos||'{}')); await runQuery('UPDATE material_recebimentos SET nome_material=?, descricao=?, quantidade_recebida=?, unidade=?, fornecedor_nome=?, fabricante=?, lote=?, numero_serie=?, nota_fiscal=?, local_armazenamento=?, observacoes=?, dados_tecnicos=?, atualizado_por=?, atualizado_em=CURRENT_TIMESTAMP WHERE id=?',[b.nome_material||old.nome_material,b.descricao??old.descricao,Number(b.quantidade_recebida||old.quantidade_recebida),unidade,b.fornecedor_nome??old.fornecedor_nome,b.fabricante??old.fabricante,b.lote??old.lote,b.numero_serie??old.numero_serie,b.nota_fiscal??old.nota_fiscal,b.local_armazenamento??old.local_armazenamento,b.observacoes??old.observacoes,JSON.stringify(dadosTecnicos),req.usuario.id,old.id]); await log(old.id,req.usuario.id,'RECEBIMENTO_ATUALIZADO',old,b); res.json(await hydrate(await assertReceipt(old.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/inspecoes', auth, async (req,res) => { try { if(!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Somente Qualidade pode inspecionar.'}); const r=await assertReceipt(req.params.id,req.tenantId), b=req.body||{}; const result=b.resultado; const statuses=['Aguardando inspeção','Em inspeção','Aprovado','Aprovado com ressalva','Bloqueado','Reprovado']; if(!statuses.includes(result)) throw new Error('Resultado de inspeção inválido.'); const a=Number(b.quantidade_aprovada||0), bl=Number(b.quantidade_bloqueada||0), rp=Number(b.quantidade_reprovada||0); if(a<0||bl<0||rp<0||a+bl+rp>Number(r.quantidade_recebida)) throw new Error('Quantidades de inspeção excedem o recebido.'); if(['Bloqueado','Reprovado','Aprovado com ressalva'].includes(result)&&!String(b.motivo||b.ressalvas||'').trim()) throw new Error('Informe justificativa para este resultado.'); await runQuery('INSERT INTO material_inspecoes (recebimento_id,inspetor_id,inspecionado_em,resultado,criterios,quantidade_aprovada,quantidade_bloqueada,quantidade_reprovada,motivo,ressalvas,providencias,prazo_tratamento,observacoes,criado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[r.id,req.usuario.id,b.inspecionado_em||new Date().toISOString(),result,b.criterios||null,a,bl,rp,b.motivo||null,b.ressalvas||null,b.providencias||null,b.prazo_tratamento||null,b.observacoes||null,req.usuario.id]); await runQuery('UPDATE material_recebimentos SET status_inspecao=?, quantidade_aprovada=?,quantidade_bloqueada=?,quantidade_reprovada=?, status=?, atualizado_por=? WHERE id=?',[result,a,bl,rp,'Aberto',req.usuario.id,r.id]); await log(r.id,req.usuario.id,'INSPECAO_REGISTRADA',null,b); res.json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/aplicacoes', auth, async (req,res) => { try { if(!can(req,APPLY_PROFILES)) return res.status(403).json({erro:'Sem permissão para registrar saída de material.'}); const r=await assertReceipt(req.params.id,req.tenantId),b=req.body||{}; if(!['Aprovado','Aprovado com ressalva'].includes(r.status_inspecao)) throw new Error('Somente material aprovado pode sair do estoque.'); const qty=Number(b.quantidade); if(!(qty>0)||qty>await balance(r)) throw new Error('Quantidade inválida ou maior que o saldo disponível.'); if(!String(b.retirado_por_nome||'').trim()) throw new Error('Informe quem retirou o material.'); if(!String(b.destino||'').trim()) throw new Error('Informe o destino ou a frente de serviço.'); if(r.tipo_codigo==='CONCRETO'&&!String(b.elemento_construtivo||'').trim()) throw new Error('Informe o elemento ou uso efetivo do concreto.'); if(b.atividade_eap_id && !(await getQuery('SELECT id FROM atividades_eap WHERE id=? AND projeto_id=?',[b.atividade_eap_id,r.projeto_id]))) throw new Error('Atividade EAP inválida.'); await runQuery('INSERT INTO material_aplicacoes (recebimento_id,projeto_id,destino,frente_servico,setor,bloco,equipamento,elemento_construtivo,atividade_eap_id,rdo_id,aplicado_em,quantidade,unidade,responsavel_id,retirado_por_nome,observacoes,tipo_movimento,criado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[r.id,r.projeto_id,b.destino,b.frente_servico||null,b.setor||null,b.bloco||null,b.equipamento||null,b.elemento_construtivo||null,b.atividade_eap_id||null,b.rdo_id||null,b.aplicado_em||new Date().toISOString(),qty,b.unidade||r.unidade,b.responsavel_id||req.usuario.id,String(b.retirado_por_nome).trim(),b.observacoes||null,b.tipo_movimento||'Saída',req.usuario.id]); const saldo=await balance(r); if(saldo===0) await runQuery("UPDATE material_recebimentos SET status='Encerrado', encerrado_em=CURRENT_TIMESTAMP WHERE id=?",[r.id]); await log(r.id,req.usuario.id,'SAIDA_DE_MATERIAL_REGISTRADA',null,b); res.json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/caminhoes', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId), b=req.body||{}; if(!can(req,WRITE_PROFILES) || r.status!=='Rascunho') return res.status(403).json({erro:'Caminhões só podem ser preenchidos no formulário, antes do envio para inspeção.'}); if(r.tipo_codigo!=='CONCRETO') throw new Error('Caminhões só podem ser registrados para recebimentos de concreto.'); if(!(Number(b.volume)>0)) throw new Error('Volume do caminhão deve ser maior que zero.'); const total=await getQuery('SELECT COALESCE(SUM(volume),0) total FROM material_caminhoes_concreto WHERE recebimento_id=?',[r.id]); const previsto=Number(r.quantidade_recebida); if(Number(total.total)+Number(b.volume)>previsto && !String(b.justificativa_divergencia||'').trim()) throw new Error('Volume acumulado superior ao declarado exige justificativa.'); await runQuery('INSERT INTO material_caminhoes_concreto (recebimento_id,volume,placa,motorista,romaneio,lote,lacre,saida_usina,chegada_obra,inicio_descarga,inicio_concretagem,fim_concretagem,slump_obtido,temperatura,resultado_inspecao,dados) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[r.id,Number(b.volume),b.placa||null,b.motorista||null,b.romaneio||null,b.lote||null,b.lacre||null,b.saida_usina||null,b.chegada_obra||null,b.inicio_descarga||null,b.inicio_concretagem||null,b.fim_concretagem||null,b.slump_obtido||null,b.temperatura||null,b.resultado_inspecao||null,JSON.stringify(b.dados||{})]); if(b.justificativa_divergencia) await runQuery('UPDATE material_recebimentos SET justificativa_divergencia=? WHERE id=?',[b.justificativa_divergencia,r.id]); await log(r.id,req.usuario.id,'CAMINHAO_CONCRETO_REGISTRADO',null,b); res.status(201).json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/corpos-prova', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId),b=req.body||{}; if(!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Somente Qualidade pode registrar corpos de prova.'}); if(r.status!=='Rascunho') throw new Error('Corpos de prova só podem ser preenchidos no formulário, antes do envio para inspeção.'); if(r.tipo_codigo!=='CONCRETO') throw new Error('Corpos de prova só podem ser registrados para recebimentos de concreto.'); if(!String(b.identificacao||'').trim()) throw new Error('Identificação do corpo de prova é obrigatória.'); const quantidade=Number(b.quantidade); if(!Number.isInteger(quantidade)||quantidade<=0) throw new Error('Informe uma quantidade inteira de corpos de prova maior que zero.'); const idades=Array.isArray(b.idades_previstas)?b.idades_previstas.filter((idade)=>String(idade).trim()):[]; await runQuery('INSERT INTO material_corpos_prova (recebimento_id,identificacao,quantidade,horario_coleta,laboratorio,idades_previstas,data_ensaio,resistencia_obtida,resultado,laudo_caminho) VALUES (?,?,?,?,?,?,?,?,?,?)',[r.id,String(b.identificacao).trim(),quantidade,b.horario_coleta||null,b.laboratorio||null,JSON.stringify(idades),b.data_ensaio||null,b.resistencia_obtida||null,b.resultado||null,b.laudo_caminho||null]); await log(r.id,req.usuario.id,'CORPO_DE_PROVA_REGISTRADO',null,b); res.status(201).json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.put('/:id/corpos-prova/:corpoProvaId', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId),b=req.body||{}; if(!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Somente Qualidade pode atualizar corpos de prova.'}); if(r.status!=='Rascunho') throw new Error('Corpos de prova só podem ser preenchidos no formulário, antes do envio para inspeção.'); if(r.tipo_codigo!=='CONCRETO') throw new Error('Corpos de prova só podem ser registrados para recebimentos de concreto.'); const corpo=await getQuery('SELECT * FROM material_corpos_prova WHERE id=? AND recebimento_id=?',[Number(req.params.corpoProvaId),r.id]); if(!corpo) { const error=new Error('Corpo de prova não encontrado.'); error.status=404; throw error; } const quantidade=b.quantidade===undefined?Number(corpo.quantidade):Number(b.quantidade); if(!Number.isInteger(quantidade)||quantidade<=0) throw new Error('Informe uma quantidade inteira de corpos de prova maior que zero.'); const identificacao=String(b.identificacao??corpo.identificacao).trim(); if(!identificacao) throw new Error('Identificação do corpo de prova é obrigatória.'); const idades=b.idades_previstas===undefined?JSON.parse(corpo.idades_previstas||'[]'):(Array.isArray(b.idades_previstas)?b.idades_previstas.filter((idade)=>String(idade).trim()):[]); const resistencia=b.resistencia_obtida===undefined?corpo.resistencia_obtida:(b.resistencia_obtida===''||b.resistencia_obtida===null?null:Number(b.resistencia_obtida)); if(resistencia!==null&&!Number.isFinite(resistencia)) throw new Error('Resistência obtida inválida.'); await runQuery('UPDATE material_corpos_prova SET identificacao=?,quantidade=?,horario_coleta=?,laboratorio=?,idades_previstas=?,data_ensaio=?,resistencia_obtida=?,resultado=?,laudo_caminho=? WHERE id=?',[identificacao,quantidade,b.horario_coleta??corpo.horario_coleta,b.laboratorio??corpo.laboratorio,JSON.stringify(idades),b.data_ensaio??corpo.data_ensaio,resistencia,b.resultado??corpo.resultado,b.laudo_caminho??corpo.laudo_caminho,corpo.id]); await log(r.id,req.usuario.id,'CORPO_DE_PROVA_ATUALIZADO',corpo,b); res.json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/encerrar', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId); if(!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Somente Gestão/Qualidade pode encerrar.'}); if((await balance(r))>0&&!String(req.body?.justificativa||'').trim()) throw new Error('Justificativa é obrigatória enquanto houver saldo.'); await runQuery("UPDATE material_recebimentos SET status='Encerrado',encerrado_em=CURRENT_TIMESTAMP,atualizado_por=? WHERE id=?",[req.usuario.id,r.id]); await log(r.id,req.usuario.id,'REGISTRO_ENCERRADO',null,req.body||{}); res.json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
router.post('/:id/rnc', auth, async (req,res) => { try { if(!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Somente Qualidade pode gerar RNC.'}); const r=await assertReceipt(req.params.id,req.tenantId); const existing=await getQuery("SELECT mr.rnc_id FROM material_rncs mr JOIN rnc x ON x.id=mr.rnc_id WHERE mr.recebimento_id=? AND x.status<>'Encerrada'",[r.id]); if(existing) return res.status(409).json({erro:'Já existe uma RNC ativa para este recebimento.',rnc_id:existing.rnc_id}); const body=req.body||{}; const created=await runQuery("INSERT INTO rnc (projeto_id,rdo_id,titulo,descricao,gravidade,status,origem,area_afetada,criado_por) VALUES (?,?,?,?,?,'Aberta',?,?,?)",[r.projeto_id,r.rdo_id||null,body.titulo||`Material ${r.nome_material} - ${r.codigo}`,body.descricao||`Divergência no recebimento ${r.codigo}. Lote: ${r.lote||'-'}. NF: ${r.nota_fiscal||'-'}.`,body.gravidade||'Média','Rastreabilidade de materiais',r.local_armazenamento||null,req.usuario.id]); await runQuery('INSERT INTO material_rncs (recebimento_id,rnc_id,criado_por) VALUES (?,?,?)',[r.id,created.lastID,req.usuario.id]); await log(r.id,req.usuario.id,'RNC_GERADA',null,{rnc_id:created.lastID}); res.status(201).json({rnc_id:created.lastID,recebimento:await hydrate(await assertReceipt(r.id,req.tenantId))}); }catch(e){err(res,e);} });
router.post('/:id/evidencias', auth, upload.single('arquivo'), async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId); if(!can(req,WRITE_PROFILES)&&!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Sem permissão para anexar evidência.'}); if(isReceiptLocked(r)) throw new Error('Anexos só podem ser alterados antes da decisão final da inspeção.'); if(!req.file) throw new Error('Arquivo obrigatório.'); const stored=path.relative(uploadsDir,req.file.path).replace(/\\/g,'/'); const x=await runQuery('INSERT INTO material_evidencias (recebimento_id,caminho_arquivo,nome_arquivo,tipo_arquivo,categoria,descricao,entidade_tipo,entidade_id,criado_por) VALUES (?,?,?,?,?,?,?,?,?)',[r.id,stored,req.file.originalname,req.file.mimetype,req.body.categoria||'Outro',req.body.descricao||null,req.body.entidade_tipo||'recebimento',req.body.entidade_id||null,req.usuario.id]); await log(r.id,req.usuario.id,'EVIDENCIA_ANEXADA',null,{arquivo:req.file.originalname}); res.status(201).json({id:x.lastID}); }catch(e){ if(req.file?.path) fs.unlink(req.file.path,()=>{}); err(res,e); } });

router.delete('/:id/evidencias/:evidenciaId', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId); if(!can(req,WRITE_PROFILES)&&!can(req,QUALITY_PROFILES)) return res.status(403).json({erro:'Sem permissão para excluir evidência.'}); if(isReceiptLocked(r)) throw new Error('Anexos só podem ser alterados antes da decisão final da inspeção.'); const evidence=await getQuery('SELECT * FROM material_evidencias WHERE id=? AND recebimento_id=?',[req.params.evidenciaId,r.id]); if(!evidence) { const error=new Error('Anexo não encontrado.'); error.status=404; throw error; } await runQuery('DELETE FROM material_evidencias WHERE id=?',[evidence.id]); const tenantUploads=path.resolve(uploadsDir, `tenant_${Number(req.tenantId)}`); const storedPath=path.resolve(uploadsDir,evidence.caminho_arquivo||''); if(storedPath.startsWith(`${tenantUploads}${path.sep}`)) fs.unlink(storedPath,()=>{}); await log(r.id,req.usuario.id,'EVIDENCIA_REMOVIDA',null,{arquivo:evidence.nome_arquivo}); res.json({mensagem:'Anexo excluído.'}); }catch(e){err(res,e);} });

router.post('/:id/enviar-inspecao', auth, async (req,res) => { try { const r=await assertReceipt(req.params.id,req.tenantId); if(!can(req,WRITE_PROFILES) || r.status !== 'Rascunho') return res.status(403).json({erro:'Somente um rascunho editável pode ser enviado para inspeção.'}); await runQuery("UPDATE material_recebimentos SET status='Aberto', status_inspecao='Aguardando inspeção', atualizado_por=?, atualizado_em=CURRENT_TIMESTAMP WHERE id=?",[req.usuario.id,r.id]); await log(r.id,req.usuario.id,'ENVIADO_PARA_INSPECAO',null,null); res.json(await hydrate(await assertReceipt(r.id,req.tenantId))); }catch(e){err(res,e);} });
module.exports = router;
