import React, { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Boxes, CheckCircle2, ClipboardCheck, Clock3, FilePlus2, Filter, Landmark, ShieldAlert, Zap } from 'lucide-react';
import Navbar from '../components/Navbar';
import { getFolhasIndicadores, getFolhasVerificacao } from '../services/api';
import './FolhasVerificacao.css';

const label = (value) => ({ RASCUNHO:'Rascunho / em inspeção', EM_ANALISE:'Pendente de aprovação', REPROVADA_BLOQUEADA:'Não conforme / bloqueada', EM_CORRECAO:'Em correção', EM_REINSPECAO:'Em reinspeção', APROVADA:'Concluída', CANCELADA:'Cancelada', CONFORME:'Conforme', NAO_CONFORME:'Não conforme', PENDENTE:'Pendente', BLOQUEADO:'Não conforme', CONFORME_COM_RESSALVAS:'Conforme com observações' }[value] || value || '-');
const frontType = (type) => type === 'TORQUE' ? 'MONTAGEM' : type;
const typeLabel = (type, modality) => type === 'ELETRICA' ? 'Elétrica' : type === 'CIVIL' ? 'Civil' : (type === 'TORQUE' || modality === 'TORQUE_ESTRUTURAL') ? 'Montagem · Torque estrutural' : 'Montagem · Conferência';
const inProgress = (status) => ['RASCUNHO','EM_ANALISE','EM_CORRECAO','EM_REINSPECAO'].includes(status);

const displayStatus = (item, siblings = []) => {
  const revision = Math.max(0, ...siblings.filter((candidate) => candidate.numero === item.numero).map((candidate) => Number(candidate.revisao) || 0));
  const opened = Math.max(Number(item.ultima_revisao_aberta || 0), revision);
  if (opened <= Number(item.revisao || 1)) return label(item.status);
  const latest = siblings.find((candidate) => candidate.numero === item.numero && Number(candidate.revisao) === opened);
  return `Rev. ${String(opened).padStart(2, '0')} ${latest?.status === 'APROVADA' ? 'aprovada' : 'aberta'}`;
};

export default function FolhasVerificacao() {
  const { projetoId } = useParams();
  const navigate = useNavigate(); const location = useLocation(); const [params, setParams] = useSearchParams();
  const [items, setItems] = useState([]); const [indicators, setIndicators] = useState([]); const [loading, setLoading] = useState(true); const [lot, setLot] = useState('');
  const routeType = location.pathname.endsWith('/montagem') ? 'MONTAGEM' : location.pathname.endsWith('/eletrica') ? 'ELETRICA' : location.pathname.endsWith('/civil') ? 'CIVIL' : '';
  const type = routeType || params.get('tipo') || ''; const status = params.get('status') || '';
  const load = async () => { setLoading(true); try { const [list, stats] = await Promise.all([getFolhasVerificacao(projetoId, { tipo: type || undefined, status: status || undefined, lote: lot || undefined }), getFolhasIndicadores(projetoId)]); setItems(list.data?.data || []); setIndicators(stats.data || []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [projetoId, type, status, lot]);
  const totals = useMemo(() => { const scoped = routeType ? indicators.filter((item) => frontType(item.tipo_folha) === routeType) : indicators; return { total: scoped.reduce((sum, item) => sum + Number(item.total || 0), 0), andamento: scoped.filter((item) => inProgress(item.status)).reduce((sum, item) => sum + Number(item.total || 0), 0), aprovadas: scoped.filter((item) => item.status === 'APROVADA').reduce((sum, item) => sum + Number(item.total || 0), 0), bloqueadas: scoped.filter((item) => ['NAO_CONFORME','BLOQUEADO'].includes(item.resultado_lote)).reduce((sum, item) => sum + Number(item.total || 0), 0) }; }, [indicators, routeType]);
  const frontStats = useMemo(() => (front) => { const scoped = indicators.filter((item) => frontType(item.tipo_folha) === front); return { total: scoped.reduce((sum, item) => sum + Number(item.total || 0), 0), andamento: scoped.filter((item) => inProgress(item.status)).reduce((sum, item) => sum + Number(item.total || 0), 0), concluidas: scoped.filter((item) => item.status === 'APROVADA').reduce((sum, item) => sum + Number(item.total || 0), 0) }; }, [indicators]);
  const setStatus = (value) => { const next = new URLSearchParams(params); value ? next.set('status', value) : next.delete('status'); setParams(next); };
  const title = routeType === 'MONTAGEM' ? 'Montagem' : routeType === 'ELETRICA' ? 'Elétrica' : routeType === 'CIVIL' ? 'Civil' : 'Folhas de verificação';
  const subtitle = routeType === 'MONTAGEM' ? 'Estruturas, fixações, conferência e torque estrutural.' : routeType === 'ELETRICA' ? 'Circuitos, conexões, ensaios e liberação elétrica.' : routeType === 'CIVIL' ? 'Escavação, fundações, concretagem, drenagem e obras complementares.' : 'Acompanhe o avanço da qualidade por frente de trabalho.';
  const kpis = [{ label: routeType ? 'Folhas criadas' : 'Total de folhas', value: totals.total, icon: ClipboardCheck, tone:'neutral' }, { label:'Em andamento', value:totals.andamento, icon:Clock3, tone:'progress' }, { label:'Concluídas', value:totals.aprovadas, icon:CheckCircle2, tone:'success' }, { label:'Não conformes / bloqueadas', value:totals.bloqueadas, icon:ShieldAlert, tone:'danger' }];
  return <><Navbar/><main className="container folhas-page folhas-dashboard">
    <header className="folhas-dashboard-header"><div><p className="eyebrow">QUALIDADE / FOLHAS DE VERIFICAÇÃO</p><h1>{title}</h1><p>{subtitle}</p></div>{routeType && <div className="header-actions"><button onClick={() => navigate(`/projeto/${projetoId}/qualidade/modelos?tipo=${routeType}`)}>Gerenciar modelos</button><button className="btn-primary" onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/nova?tipo=${routeType}`)}><FilePlus2 size={17}/> {routeType === 'MONTAGEM' ? 'Nova FV-MON' : routeType === 'ELETRICA' ? 'Nova FV-ELE' : 'Nova FV-CIV'}</button></div>}</header>
    <nav className="folhas-tabs folhas-dashboard-tabs"><button className={!routeType && !status ? 'active' : ''} onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas`)}>Visão geral</button><button className={routeType === 'MONTAGEM' ? 'active' : ''} onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/montagem`)}>Montagem</button><button className={routeType === 'ELETRICA' ? 'active' : ''} onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/eletrica`)}>Elétrica</button><button className={routeType === 'CIVIL' ? 'active' : ''} onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/civil`)}>Civil</button><span className="tab-separator"/><button className={status === 'EM_ANALISE' ? 'active' : ''} onClick={() => setStatus(status === 'EM_ANALISE' ? '' : 'EM_ANALISE')}>Pendentes</button><button className={status === 'REPROVADA_BLOQUEADA' ? 'active' : ''} onClick={() => setStatus(status === 'REPROVADA_BLOQUEADA' ? '' : 'REPROVADA_BLOQUEADA')}>Reprovadas</button></nav>
    {!routeType && <section className="front-overview" aria-label="Resumo por frente">
      <button className="front-overview-card front-overview-card--montagem" onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/montagem`)}><span className="front-card-icon"><Boxes size={22}/></span><div className="front-card-copy"><span>FRENTE DE TRABALHO</span><h2>Montagem</h2><p>Estruturas, componentes, fixações e torque estrutural.</p></div><div className="front-card-footer"><div><b>{frontStats('MONTAGEM').total}</b><small>folhas</small><span>{frontStats('MONTAGEM').andamento} em andamento · {frontStats('MONTAGEM').concluidas} concluídas</span></div><ArrowUpRight size={21}/></div></button>
      <button className="front-overview-card front-overview-card--eletrica" onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/eletrica`)}><span className="front-card-icon"><Zap size={22}/></span><div className="front-card-copy"><span>FRENTE DE TRABALHO</span><h2>Elétrica</h2><p>Circuitos, cabos, conexões, ensaios e liberação.</p></div><div className="front-card-footer"><div><b>{frontStats('ELETRICA').total}</b><small>folhas</small><span>{frontStats('ELETRICA').andamento} em andamento · {frontStats('ELETRICA').concluidas} concluídas</span></div><ArrowUpRight size={21}/></div></button>
      <button className="front-overview-card front-overview-card--civil" onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/civil`)}><span className="front-card-icon"><Landmark size={22}/></span><div className="front-card-copy"><span>FRENTE DE TRABALHO</span><h2>Civil</h2><p>Escavação, fundações, concretagem, drenagem e complementares.</p></div><div className="front-card-footer"><div><b>{frontStats('CIVIL').total}</b><small>folhas</small><span>{frontStats('CIVIL').andamento} em andamento · {frontStats('CIVIL').concluidas} concluídas</span></div><ArrowUpRight size={21}/></div></button>
    </section>}
    <section className="dashboard-kpis">{kpis.map(({ label, value, icon: Icon, tone }) => <article className={`dashboard-kpi dashboard-kpi--${tone}`} key={label}><span className="dashboard-kpi-icon"><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong></div></article>)}</section>
    <section className="folhas-list-card dashboard-list"><div className="dashboard-list-head"><div><span className="section-kicker">ACOMPANHAMENTO</span><h2><ClipboardCheck size={21}/>{routeType ? `Folhas de ${routeType === 'MONTAGEM' ? 'Montagem' : routeType === 'ELETRICA' ? 'Elétrica' : 'Civil'}` : 'Folhas recentes'}</h2></div><label className="dashboard-search"><Filter size={16}/><input value={lot} placeholder="Buscar por lote" onChange={(event) => setLot(event.target.value)} /></label></div>{loading ? <p className="folhas-empty">Carregando folhas…</p> : items.length === 0 ? <div className="dashboard-empty"><ClipboardCheck size={25}/><div><strong>Nenhuma folha encontrada</strong><span>{lot ? 'Tente outro código ou limpe a busca.' : 'Quando uma verificação for criada, ela aparecerá aqui.'}</span></div></div> : <div className="folhas-table-wrap"><table><thead><tr><th>Número</th><th>Frente / modalidade</th><th>Lote</th><th>Data</th><th>Medições</th><th>Resultado</th><th>Status</th><th>RNC</th></tr></thead><tbody>{items.map((item) => { const identification = typeof item.identificacao === 'string' ? JSON.parse(item.identificacao || '{}') : item.identificacao || {}; const summary = typeof item.resumo === 'string' ? JSON.parse(item.resumo || '{}') : item.resumo || {}; return <tr key={item.id} tabIndex="0" onClick={() => navigate(`/projeto/${projetoId}/qualidade/folhas/${item.id}`)}><td><strong>{item.numero}</strong><small>{item.modelo_nome}</small><small>Rev. {String(item.revisao || 1).padStart(2, '0')}</small></td><td><span className={`front-pill front-pill--${frontType(item.tipo_folha).toLowerCase()}`}>{typeLabel(item.tipo_folha, identification.modalidade)}</span></td><td><strong className="table-lot">{identification.codigo_lote || 'Não informado'}</strong></td><td>{item.criado_em ? new Date(item.criado_em).toLocaleDateString('pt-BR') : '-'}</td><td>{summary.measured || 0}</td><td><span className={`status status-${String(item.resultado_lote || '').toLowerCase()}`}>{label(item.resultado_lote)}</span></td><td>{displayStatus(item, items)}</td><td>{item.rnc_id ? <span className="rnc-badge">#{item.rnc_id}</span> : '—'}</td></tr>; })}</tbody></table></div>}</section>
  </main></>;
}
