import React, { useEffect, useMemo, useState } from 'react';
import { Plus } from 'lucide-react';
import { addFolhaEletricaCircuito, addFolhaEletricaRegistro, getFolhasContexto } from '../services/api';

const emptyCircuit = { tag: '', origem: '', destino: '', sistema_eletrico: '', classe_tensao: '', tensao_nominal: '', corrente_nominal: '', rota: '', trecho: '' };
const emptyTest = { tipo: 'CONTINUIDADE', circuito_id: '', procedimento: '', criterio: '', valor_medido: '', unidade: '', limite_inferior: '', limite_superior: '', observacao: '' };

export default function FolhaEletricaPanel({ sheet, editable, onChanged }) {
  const [circuit, setCircuit] = useState(emptyCircuit); const [test, setTest] = useState(emptyTest); const [assets, setAssets] = useState([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const data = sheet.eletrica || { circuitos: [], cabos: [], equipamentos: [], conexoes: [], torques: [], ensaios: [] };
  const config = useMemo(() => { try { const snapshot = typeof sheet.modelo_snapshot === 'string' ? JSON.parse(sheet.modelo_snapshot || '{}') : sheet.modelo_snapshot || {}; return snapshot.configuracao || {}; } catch { return {}; } }, [sheet.modelo_snapshot]);
  const requiredTests = config.ensaios_obrigatorios || [];
  useEffect(() => { getFolhasContexto(sheet.projeto_id).then((response) => setAssets(response.data?.ativos || [])).catch(() => setAssets([])); }, [sheet.projeto_id]);
  const saveCircuit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await addFolhaEletricaCircuito(sheet.id, circuit); setCircuit(emptyCircuit); await onChanged(); } catch (err) { setError(err.response?.data?.erro || 'Não foi possível registrar o circuito.'); } finally { setSaving(false); } };
  const saveTest = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const instrument = assets.find((asset) => String(asset.id) === String(test.instrumento_id)); await addFolhaEletricaRegistro(sheet.id, 'ensaios', { ...test, instrumento: instrument || {}, circuito_id: test.circuito_id || null, limite_inferior: test.limite_inferior || null, limite_superior: test.limite_superior || null }); setTest(emptyTest); await onChanged(); } catch (err) { setError(err.response?.data?.erro || 'Não foi possível registrar o ensaio.'); } finally { setSaving(false); } };
  return <section className="folha-eletrica-panel">
    <h2>Registros elétricos</h2><p>Registre circuitos e ensaios desta FV-ELE. Cabos, conexões, equipamentos e torque elétrico usam os mesmos registros rastreáveis da folha.</p>{requiredTests.length > 0 && <aside className="electrical-required-tests"><strong>Ensaios configurados para este modelo</strong>{requiredTests.map((item) => <span key={item.tipo}>{item.tipo.replaceAll('_', ' ')}{item.obrigatorio !== false ? ' · obrigatório' : ''}{item.exige_instrumento ? ' · instrumento calibrado' : ''}</span>)}</aside>}{error && <div className="folhas-error">{error}</div>}
    <div className="folhas-kpis"><article><span>Circuitos</span><strong>{data.circuitos.length}</strong></article><article><span>Cabos</span><strong>{data.cabos.length}</strong></article><article><span>Conexões</span><strong>{data.conexoes.length}</strong></article><article><span>Ensaios</span><strong>{data.ensaios.length}</strong></article></div>
    {editable && <div className="folha-eletrica-forms"><form onSubmit={saveCircuit}><h3>Novo circuito</h3><div className="folha-grid"><label>TAG / circuito<input required value={circuit.tag} onChange={e=>setCircuit({...circuit,tag:e.target.value})}/></label><label>Origem<input value={circuit.origem} onChange={e=>setCircuit({...circuit,origem:e.target.value})}/></label><label>Destino<input value={circuit.destino} onChange={e=>setCircuit({...circuit,destino:e.target.value})}/></label><label>Sistema elétrico<input value={circuit.sistema_eletrico} onChange={e=>setCircuit({...circuit,sistema_eletrico:e.target.value})}/></label><label>Classe de tensão<input value={circuit.classe_tensao} onChange={e=>setCircuit({...circuit,classe_tensao:e.target.value})}/></label><label>Trecho<input value={circuit.trecho} onChange={e=>setCircuit({...circuit,trecho:e.target.value})}/></label></div><button className="btn-primary" disabled={saving}><Plus size={15}/> Adicionar circuito</button></form><form onSubmit={saveTest}><h3>Novo ensaio</h3><div className="folha-grid"><label>Tipo<select value={test.tipo} onChange={e=>setTest({...test,tipo:e.target.value})}>{['CONTINUIDADE','CONTINUIDADE_PE','RESISTENCIA_ISOLACAO','RESISTENCIA_ATERRAMENTO','POLARIDADE','SEQUENCIA_FASES','TENSAO','CORRENTE','TESTE_FUNCIONAL','DR_RCD','INTERTRAVAMENTO','COMANDO','PROTECAO','SINALIZACAO','OUTRO'].map(x=><option key={x}>{x}</option>)}</select></label><label>Circuito<select value={test.circuito_id} onChange={e=>setTest({...test,circuito_id:e.target.value})}><option value="">Não vinculado</option>{data.circuitos.map(x=><option key={x.id} value={x.id}>{x.tag}</option>)}</select></label><label>Valor medido<input type="number" step="any" value={test.valor_medido} onChange={e=>setTest({...test,valor_medido:e.target.value})}/></label><label>Unidade<input value={test.unidade} onChange={e=>setTest({...test,unidade:e.target.value})}/></label><label>Critério<input value={test.criterio} onChange={e=>setTest({...test,criterio:e.target.value})}/></label><label>Instrumento<select value={test.instrumento_id || ''} onChange={e=>setTest({...test,instrumento_id:e.target.value})}><option value="">Não informado</option>{assets.map((asset)=><option key={asset.id} value={asset.id}>{asset.codigo} — {asset.nome}</option>)}</select></label></div><button className="btn-primary" disabled={saving}><Plus size={15}/> Registrar ensaio</button></form></div>}
    <div className="folhas-table-wrap"><table><thead><tr><th>Circuito</th><th>Origem</th><th>Destino</th><th>Resultado</th><th>Bloqueado</th></tr></thead><tbody>{data.circuitos.length ? data.circuitos.map(x=><tr key={x.id}><td>{x.tag}</td><td>{x.origem || '—'}</td><td>{x.destino || '—'}</td><td>{x.resultado}</td><td>{x.bloqueado ? 'Sim' : 'Não'}</td></tr>) : <tr><td colSpan="5">Nenhum circuito registrado.</td></tr>}</tbody></table></div>
    <div className="folhas-table-wrap"><table><thead><tr><th>Ensaio</th><th>Circuito</th><th>Valor</th><th>Resultado</th><th>Data</th></tr></thead><tbody>{data.ensaios.length ? data.ensaios.map(x=><tr key={x.id}><td>{x.tipo}</td><td>{data.circuitos.find(c=>c.id===x.circuito_id)?.tag || '—'}</td><td>{x.valor_medido ?? '—'} {x.unidade || ''}</td><td>{x.resultado}</td><td>{x.realizado_em ? new Date(x.realizado_em).toLocaleString('pt-BR') : '—'}</td></tr>) : <tr><td colSpan="5">Nenhum ensaio registrado.</td></tr>}</tbody></table></div>
  </section>;
}
