const assert = require('assert');
const rules = require('../services/folhasVerificacaoService');

const limitsPercent = rules.calculateLimits({ expected: '55', toleranceType: 'PERCENTUAL', tolerance: '5' });
assert.deepStrictEqual(limitsPercent, { expected: '55', lower: '52.25', upper: '57.75' });
const limitsAbsolute = rules.calculateLimits({ expected: '55', toleranceType: 'ABSOLUTA', tolerance: '2.5' });
assert.deepStrictEqual(limitsAbsolute, { expected: '55', lower: '52.5', upper: '57.5' });
const limitsManual = rules.calculateLimits({ expected: '55', toleranceType: 'MANUAL', lowerLimit: '50', upperLimit: '60' });
assert.deepStrictEqual(limitsManual, { expected: '55', lower: '50', upper: '60' });
assert.strictEqual(rules.calculateMeasurementResult({ value:'52.25', lower:'52.25', upper:'57.75' }), rules.RESULT.CONFORME);
assert.strictEqual(rules.calculateMeasurementResult({ value:'57.75', lower:'52.25', upper:'57.75' }), rules.RESULT.CONFORME);
assert.strictEqual(rules.calculateMeasurementResult({ value:'52.24', lower:'52.25', upper:'57.75' }), rules.RESULT.NAO_CONFORME);
assert.strictEqual(rules.calculateMeasurementResult({ value:'57.76', lower:'52.25', upper:'57.75' }), rules.RESULT.NAO_CONFORME);
const cZero = rules.summarizeLot({ population: 20, sampleSize: 2, acceptanceCriterion: rules.ACCEPTANCE.C_ZERO, measurements:[{result:rules.RESULT.CONFORME},{result:rules.RESULT.NAO_CONFORME}] });
assert.strictEqual(cZero.result, rules.RESULT.NAO_CONFORME);
const allowedNc = rules.summarizeLot({ population: 20, sampleSize: 2, acceptanceCriterion: rules.ACCEPTANCE.MAX_NC, maxNonConformities:1, measurements:[{result:rules.RESULT.CONFORME},{result:rules.RESULT.NAO_CONFORME}] });
assert.strictEqual(allowedNc.result, rules.RESULT.COM_RESSALVAS);
const incomplete = rules.summarizeLot({ population:20, sampleSize:3, measurements:[{result:rules.RESULT.CONFORME}] });
assert.strictEqual(incomplete.result, rules.RESULT.PENDENTE);
const groupedMeasurements = rules.summarizeLot({ population:225, sampleSize:225, measurements:[{result:rules.RESULT.CONFORME,quantity:12}] });
assert.strictEqual(groupedMeasurements.measured, 12);
assert.strictEqual(groupedMeasurements.pending, 213);
assert.strictEqual(groupedMeasurements.result, rules.RESULT.PENDENTE);
assert.throws(() => rules.summarizeLot({ population:1, sampleSize:1, measurements:[{result:rules.RESULT.CONFORME,quantity:0}] }), /quantidade verificada/i);
assert.throws(() => rules.assertInstrument({ expectedTorque:'55', rangeMin:'10', rangeMax:'50' }), /fora da faixa/);
assert.throws(() => rules.assertInstrument({ calibrationValidUntil:'2000-01-01' }), /calibração vencida/);
assert.throws(() => rules.assertInstrument({ status:'EM_MANUTENCAO' }), /indisponível/);
assert.doesNotThrow(() => rules.assertInstrument({ status:'EM_MANUTENCAO', exceptionReleased:true, exceptionJustification:'Liberado pelo gestor' }));
assert.strictEqual(rules.isImmutable(rules.STATUS.APROVADA), true);
assert.strictEqual(rules.isImmutable(rules.STATUS.RASCUNHO), false);
assert.throws(() => rules.assertTransition(rules.STATUS.APROVADA, rules.STATUS.RASCUNHO));
const linkedTorque = rules.summarizeLot({ population:1, sampleSize:1, measurements:[{result:rules.RESULT.CONFORME}], requiredTorqueLinks:[{required:true,status:rules.STATUS.EM_ANALISE,result:rules.RESULT.PENDENTE}] });
assert.strictEqual(linkedTorque.result, rules.RESULT.BLOQUEADO);
console.log('folhasVerificacaoService.test.js: OK');
